api-definition:
- changed-files:
  - any-glob-to-any-file: ['yaml/*']
code-gen:
- changed-files:
  - any-glob-to-any-file: ['pom.xml']
documentation:
- changed-files:
  - any-glob-to-any-file: ['doc/source/**/*', 'examples/**/*']
maintenance:
- changed-files:
  - any-glob-to-any-file: ['.github/**/*', '.flake8', 'pyproject.toml']
dependencies:
- changed-files:
  - any-glob-to-any-file: ['poetry.lock']