changelog:
  exclude:
    labels:
      - dependencies
  categories:
    - title: "API Definition"
      labels:
        - api-definition
    - title: "Features"
      labels:
        - enhancement
    - title: "Documentation"
      labels:
        - documentation
    - title: "Maintenance"
      labels:
        - maintenance
    - title: "Other changes"
      labels:
        - "*"