"""
    MI Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import TYPE_CHECKING, Any, BinaryIO, Optional, Union  # noqa: F401

from . import ModelBase, Unset, Unset_Type
from ansys.grantami.serverapi_openapi.v252.models.gsa_version_control_error_detail import GsaVersionControlErrorDetail  # noqa: F401


if TYPE_CHECKING:
    from datetime import datetime
    import pathlib
    from . import *


class GsaNotTheLatestVersionErrorDetail(GsaVersionControlErrorDetail):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes
    ----------
    swagger_types: dict[str, str]
        The key is attribute name and the value is attribute type.
    attribute_map: dict[str, str]
        The key is attribute name and the value is json key in definition.
    subtype_mapping: dict[str, str]
        The key is the unmangled property name and the value is the corresponding type.
    discriminator: Optional[str]
        Name of the property used as discriminator for subtypes.
    """
    swagger_types: dict[str, str] = {
        "message": "str",
        "reason": "str",
        "newer_version": "GsaSlimRecordVersion",
    }

    attribute_map: dict[str, str] = {
        "message": "message",
        "reason": "reason",
        "newer_version": "newerVersion",
    }

    subtype_mapping: dict[str, str] = {
        "newerVersion": "GsaSlimRecordVersion",
    }

    discriminator: Optional[str] = None

    def __init__(self, *, message: "str", reason: "str" = "notTheLatestVersion", newer_version: "Union[GsaSlimRecordVersion, Unset_Type]" = Unset,) -> None:
        """GsaNotTheLatestVersionErrorDetail - a model defined in Swagger

        Parameters
        ----------
        message: str
        reason: str
        newer_version: GsaSlimRecordVersion, optional
        """
        super().__init__(message=message, reason=reason)
        self._newer_version: Union[GsaSlimRecordVersion, Unset_Type] = Unset

        if newer_version is not Unset:
            self.newer_version = newer_version

    @property
    def newer_version(self) -> "Union[GsaSlimRecordVersion, Unset_Type]":
        """Gets the newer_version of this GsaNotTheLatestVersionErrorDetail.

        Returns
        -------
        Union[GsaSlimRecordVersion, Unset_Type]
            The newer_version of this GsaNotTheLatestVersionErrorDetail.
        """
        return self._newer_version

    @newer_version.setter
    def newer_version(self, newer_version: "Union[GsaSlimRecordVersion, Unset_Type]") -> None:
        """Sets the newer_version of this GsaNotTheLatestVersionErrorDetail.

        Parameters
        ----------
        newer_version: Union[GsaSlimRecordVersion, Unset_Type]
            The newer_version of this GsaNotTheLatestVersionErrorDetail.
        """
        # Field is not nullable
        if newer_version is None:
            raise ValueError("Invalid value for 'newer_version', must not be 'None'")
        self._newer_version = newer_version

    @classmethod
    def get_real_child_model(cls, data: dict[str, str]) -> str:
        """Raises a NotImplementedError for a type without a discriminator defined.

        Parameters
        ----------
        data: ModelBase
            Object representing a subclass of this class

        Raises
        ------
        NotImplementedError
            This class has no discriminator, and hence no subclasses
        """
        raise NotImplementedError()

    def __repr__(self) -> str:
        """For 'print' and 'pprint'"""
        return self.to_str()

    def __eq__(self, other: Any) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, GsaNotTheLatestVersionErrorDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other

