repos:

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    files: '^ansys-grantami-serverapi-openapi/(src|tests)'
    args:
      - '--line-length=100'

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort
    files: '^ansys-grantami-serverapi-openapi/(src|tests)'

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
  - id: debug-statements
  - id: check-merge-conflict
  - id: trailing-whitespace

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.5.2
  hooks:
    - id: add-license-headers
      args:
      - --start_year=2023
      files: 'ansys-grantami-serverapi-openapi/(src|tests)/.*\.(py)'
