# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""
    MI Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import TYPE_CHECKING, Any, Dict, List, Optional  # noqa: F401

from . import ModelBase

if TYPE_CHECKING:
    from . import *


class GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter(
    ModelBase
):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes
    ----------
    swagger_types: Dict[str, str]
        The key is attribute name and the value is attribute type.
    attribute_map: Dict[str, str]
        The key is attribute name and the value is json key in definition.
    subtype_mapping: Dict[str, str]
        The key is the unmangled property name and the value is the corresponding type.
    discriminator: Optional[str]
        Name of the property used as discriminator for subtypes.
    """
    swagger_types = {
        "parameter": "GrantaServerApiSchemaSlimEntitiesSlimEntity",
        "default_value": "float",
        "interpolation_method": "GrantaServerApiSchemaAttributesAttributeInterpolationMethod",
        "scale_type": "GrantaServerApiSchemaAttributesAttributeScaleType",
    }

    attribute_map = {
        "parameter": "parameter",
        "default_value": "defaultValue",
        "interpolation_method": "interpolationMethod",
        "scale_type": "scaleType",
    }

    subtype_mapping = {
        "parameter": "GrantaServerApiSchemaSlimEntitiesSlimEntity",
        "interpolationMethod": "GrantaServerApiSchemaAttributesAttributeInterpolationMethod",
        "scaleType": "GrantaServerApiSchemaAttributesAttributeScaleType",
    }

    discriminator = None

    def __init__(
        self,
        *,
        parameter: "GrantaServerApiSchemaSlimEntitiesSlimEntity",
        default_value: "Optional[float]" = None,
        interpolation_method: "Optional[GrantaServerApiSchemaAttributesAttributeInterpolationMethod]" = None,
        scale_type: "Optional[GrantaServerApiSchemaAttributesAttributeScaleType]" = None,
    ) -> None:
        """GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter - a model defined in Swagger

        Parameters
        ----------
            parameter: GrantaServerApiSchemaSlimEntitiesSlimEntity
            default_value: float, optional
            interpolation_method: GrantaServerApiSchemaAttributesAttributeInterpolationMethod, optional
            scale_type: GrantaServerApiSchemaAttributesAttributeScaleType, optional
        """
        self._parameter = None
        self._default_value = None
        self._interpolation_method = None
        self._scale_type = None

        self.parameter = parameter
        if default_value is not None:
            self.default_value = default_value
        if interpolation_method is not None:
            self.interpolation_method = interpolation_method
        if scale_type is not None:
            self.scale_type = scale_type

    @property
    def parameter(self) -> "GrantaServerApiSchemaSlimEntitiesSlimEntity":
        """Gets the parameter of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.

        Returns
        -------
        GrantaServerApiSchemaSlimEntitiesSlimEntity
            The parameter of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.
        """
        return self._parameter

    @parameter.setter
    def parameter(self, parameter: "GrantaServerApiSchemaSlimEntitiesSlimEntity") -> None:
        """Sets the parameter of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.

        Parameters
        ----------
        parameter: GrantaServerApiSchemaSlimEntitiesSlimEntity
            The parameter of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.
        """
        if parameter is None:
            raise ValueError("Invalid value for 'parameter', must not be 'None'")
        self._parameter = parameter

    @property
    def default_value(self) -> "float":
        """Gets the default_value of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.

        Returns
        -------
        float
            The default_value of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.
        """
        return self._default_value

    @default_value.setter
    def default_value(self, default_value: "float") -> None:
        """Sets the default_value of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.

        Parameters
        ----------
        default_value: float
            The default_value of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.
        """
        self._default_value = default_value

    @property
    def interpolation_method(
        self,
    ) -> "GrantaServerApiSchemaAttributesAttributeInterpolationMethod":
        """Gets the interpolation_method of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.

        Returns
        -------
        GrantaServerApiSchemaAttributesAttributeInterpolationMethod
            The interpolation_method of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.
        """
        return self._interpolation_method

    @interpolation_method.setter
    def interpolation_method(
        self,
        interpolation_method: "GrantaServerApiSchemaAttributesAttributeInterpolationMethod",
    ) -> None:
        """Sets the interpolation_method of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.

        Parameters
        ----------
        interpolation_method: GrantaServerApiSchemaAttributesAttributeInterpolationMethod
            The interpolation_method of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.
        """
        self._interpolation_method = interpolation_method

    @property
    def scale_type(self) -> "GrantaServerApiSchemaAttributesAttributeScaleType":
        """Gets the scale_type of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.

        Returns
        -------
        GrantaServerApiSchemaAttributesAttributeScaleType
            The scale_type of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.
        """
        return self._scale_type

    @scale_type.setter
    def scale_type(self, scale_type: "GrantaServerApiSchemaAttributesAttributeScaleType") -> None:
        """Sets the scale_type of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.

        Parameters
        ----------
        scale_type: GrantaServerApiSchemaAttributesAttributeScaleType
            The scale_type of this GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter.
        """
        self._scale_type = scale_type

    @classmethod
    def get_real_child_model(cls, data: ModelBase) -> str:
        """Raises a NotImplementedError for a type without a discriminator defined.

        Parameters
        ----------
        data: ModelBase
            Object representing a subclass of this class

        Raises
        ------
        NotImplementedError
            This class has no discriminator, and hence no subclasses
        """
        raise NotImplementedError()

    def __repr__(self) -> str:
        """For 'print' and 'pprint'"""
        return self.to_str()

    def __eq__(self, other: Any) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(
            other,
            GrantaServerApiSchemaAttributesCreateAttributesCreateFloatFunctionalAttributeParameter,
        ):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
