# Copyright (C) 2023 - 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""
MI Server API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import TYPE_CHECKING, Any, BinaryIO, Optional  # noqa: F401

from . import ModelBase, Unset, Unset_Type

if TYPE_CHECKING:
    from datetime import datetime
    import pathlib

    from . import *


class GsaParameterDefaultValue(ModelBase):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes
    ----------
    swagger_types: dict[str, str]
        The key is attribute name and the value is attribute type.
    attribute_map: dict[str, str]
        The key is attribute name and the value is json key in definition.
    subtype_mapping: dict[str, str]
        The key is the unmangled property name and the value is the corresponding type.
    discriminator: Optional[str]
        Name of the property used as discriminator for subtypes.
    """
    swagger_types: dict[str, str] = {
        "source": "GsaParameterDefaultValueSource",
        "value_in_database_units": "float",
        "parameter_value_guid": "str",
    }

    attribute_map: dict[str, str] = {
        "source": "source",
        "value_in_database_units": "valueInDatabaseUnits",
        "parameter_value_guid": "parameterValueGuid",
    }

    subtype_mapping: dict[str, str] = {
        "source": "GsaParameterDefaultValueSource",
    }

    discriminator: Optional[str] = None

    def __init__(
        self,
        *,
        source: "GsaParameterDefaultValueSource",
        value_in_database_units: "float",
        parameter_value_guid: "str | None | Unset_Type" = Unset,
    ) -> None:
        """GsaParameterDefaultValue - a model defined in Swagger

        Parameters
        ----------
        source: GsaParameterDefaultValueSource
        value_in_database_units: float
        parameter_value_guid: str | None, optional
        """
        self._value_in_database_units: float
        self._parameter_value_guid: str | None | Unset_Type = Unset
        self._source: GsaParameterDefaultValueSource

        self.value_in_database_units = value_in_database_units
        if parameter_value_guid is not Unset:
            self.parameter_value_guid = parameter_value_guid
        self.source = source

    @property
    def value_in_database_units(self) -> "float":
        """Gets the value_in_database_units of this GsaParameterDefaultValue.
        The numeric value of the default

        Returns
        -------
        float
            The value_in_database_units of this GsaParameterDefaultValue.
        """
        return self._value_in_database_units

    @value_in_database_units.setter
    def value_in_database_units(self, value_in_database_units: "float") -> None:
        """Sets the value_in_database_units of this GsaParameterDefaultValue.
        The numeric value of the default

        Parameters
        ----------
        value_in_database_units: float
            The value_in_database_units of this GsaParameterDefaultValue.
        """
        # Field is not nullable
        if value_in_database_units is None:
            raise ValueError("Invalid value for 'value_in_database_units', must not be 'None'")
        # Field is required
        if value_in_database_units is Unset:  # type: ignore[comparison-overlap, unused-ignore]
            raise ValueError("Invalid value for 'value_in_database_units', must not be 'Unset'")
        self._value_in_database_units = value_in_database_units

    @property
    def parameter_value_guid(self) -> "str | None | Unset_Type":
        """Gets the parameter_value_guid of this GsaParameterDefaultValue.
        The optional GUID of the defined parameter value that this corresponds to. For unrestricted numeric parameters, this could be null

        Returns
        -------
        str | None | Unset_Type
            The parameter_value_guid of this GsaParameterDefaultValue.
        """
        return self._parameter_value_guid

    @parameter_value_guid.setter
    def parameter_value_guid(self, parameter_value_guid: "str | None | Unset_Type") -> None:
        """Sets the parameter_value_guid of this GsaParameterDefaultValue.
        The optional GUID of the defined parameter value that this corresponds to. For unrestricted numeric parameters, this could be null

        Parameters
        ----------
        parameter_value_guid: str | None | Unset_Type
            The parameter_value_guid of this GsaParameterDefaultValue.
        """
        self._parameter_value_guid = parameter_value_guid

    @property
    def source(self) -> "GsaParameterDefaultValueSource":
        """Gets the source of this GsaParameterDefaultValue.

        Returns
        -------
        GsaParameterDefaultValueSource
            The source of this GsaParameterDefaultValue.
        """
        return self._source

    @source.setter
    def source(self, source: "GsaParameterDefaultValueSource") -> None:
        """Sets the source of this GsaParameterDefaultValue.

        Parameters
        ----------
        source: GsaParameterDefaultValueSource
            The source of this GsaParameterDefaultValue.
        """
        # Field is not nullable
        if source is None:
            raise ValueError("Invalid value for 'source', must not be 'None'")
        # Field is required
        if source is Unset:  # type: ignore[comparison-overlap, unused-ignore]
            raise ValueError("Invalid value for 'source', must not be 'Unset'")
        self._source = source

    @classmethod
    def get_real_child_model(cls, data: dict[str, str]) -> str:
        """Raises a NotImplementedError for a type without a discriminator defined.

        Parameters
        ----------
        data: ModelBase
            Object representing a subclass of this class

        Raises
        ------
        NotImplementedError
            This class has no discriminator, and hence no subclasses
        """
        raise NotImplementedError()

    def __repr__(self) -> str:
        """For 'print' and 'pprint'"""
        return self.to_str()

    def __eq__(self, other: Any) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, GsaParameterDefaultValue):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
