# Copyright (C) 2023 - 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""
MI Server API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import TYPE_CHECKING, Any, BinaryIO, Optional  # noqa: F401

from . import ModelBase, Unset, Unset_Type

if TYPE_CHECKING:
    from datetime import datetime
    import pathlib

    from . import *


class GsaLongRunningOperation(ModelBase):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes
    ----------
    swagger_types: dict[str, str]
        The key is attribute name and the value is attribute type.
    attribute_map: dict[str, str]
        The key is attribute name and the value is json key in definition.
    subtype_mapping: dict[str, str]
        The key is the unmangled property name and the value is the corresponding type.
    discriminator: Optional[str]
        Name of the property used as discriminator for subtypes.
    """
    swagger_types: dict[str, str] = {
        "identifier": "str",
        "status": "GsaLongRunningStatus",
        "http_status_code": "int",
        "number_of_completed_tasks": "float",
        "number_of_tasks": "int",
        "response": "object",
    }

    attribute_map: dict[str, str] = {
        "identifier": "identifier",
        "status": "status",
        "http_status_code": "httpStatusCode",
        "number_of_completed_tasks": "numberOfCompletedTasks",
        "number_of_tasks": "numberOfTasks",
        "response": "response",
    }

    subtype_mapping: dict[str, str] = {
        "status": "GsaLongRunningStatus",
    }

    discriminator: Optional[str] = None

    def __init__(
        self,
        *,
        identifier: "str",
        status: "GsaLongRunningStatus",
        http_status_code: "int | None | Unset_Type" = Unset,
        number_of_completed_tasks: "float | None | Unset_Type" = Unset,
        number_of_tasks: "int | None | Unset_Type" = Unset,
        response: "object | None | Unset_Type" = Unset,
    ) -> None:
        """GsaLongRunningOperation - a model defined in Swagger

        Parameters
        ----------
        identifier: str
        status: GsaLongRunningStatus
        http_status_code: int | None, optional
        number_of_completed_tasks: float | None, optional
        number_of_tasks: int | None, optional
        response: object | None, optional
        """
        self._identifier: str
        self._status: GsaLongRunningStatus
        self._number_of_completed_tasks: float | None | Unset_Type = Unset
        self._number_of_tasks: int | None | Unset_Type = Unset
        self._http_status_code: int | None | Unset_Type = Unset
        self._response: object | None | Unset_Type = Unset

        self.identifier = identifier
        self.status = status
        if number_of_completed_tasks is not Unset:
            self.number_of_completed_tasks = number_of_completed_tasks
        if number_of_tasks is not Unset:
            self.number_of_tasks = number_of_tasks
        if http_status_code is not Unset:
            self.http_status_code = http_status_code
        if response is not Unset:
            self.response = response

    @property
    def identifier(self) -> "str":
        """Gets the identifier of this GsaLongRunningOperation.

        Returns
        -------
        str
            The identifier of this GsaLongRunningOperation.
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier: "str") -> None:
        """Sets the identifier of this GsaLongRunningOperation.

        Parameters
        ----------
        identifier: str
            The identifier of this GsaLongRunningOperation.
        """
        # Field is not nullable
        if identifier is None:
            raise ValueError("Invalid value for 'identifier', must not be 'None'")
        # Field is required
        if identifier is Unset:  # type: ignore[comparison-overlap, unused-ignore]
            raise ValueError("Invalid value for 'identifier', must not be 'Unset'")
        self._identifier = identifier

    @property
    def status(self) -> "GsaLongRunningStatus":
        """Gets the status of this GsaLongRunningOperation.

        Returns
        -------
        GsaLongRunningStatus
            The status of this GsaLongRunningOperation.
        """
        return self._status

    @status.setter
    def status(self, status: "GsaLongRunningStatus") -> None:
        """Sets the status of this GsaLongRunningOperation.

        Parameters
        ----------
        status: GsaLongRunningStatus
            The status of this GsaLongRunningOperation.
        """
        # Field is not nullable
        if status is None:
            raise ValueError("Invalid value for 'status', must not be 'None'")
        # Field is required
        if status is Unset:  # type: ignore[comparison-overlap, unused-ignore]
            raise ValueError("Invalid value for 'status', must not be 'Unset'")
        self._status = status

    @property
    def number_of_completed_tasks(self) -> "float | None | Unset_Type":
        """Gets the number_of_completed_tasks of this GsaLongRunningOperation.
        The total number of tasks that have been completed so far.  May be null if the tasks are not easily quantifiable.  Will change as the operation progresses.  May be fractional if a task is partially complete.  All tasks completed does not necessarily mean the operation has completed, there may be additional work.

        Returns
        -------
        float | None | Unset_Type
            The number_of_completed_tasks of this GsaLongRunningOperation.
        """
        return self._number_of_completed_tasks

    @number_of_completed_tasks.setter
    def number_of_completed_tasks(
        self, number_of_completed_tasks: "float | None | Unset_Type"
    ) -> None:
        """Sets the number_of_completed_tasks of this GsaLongRunningOperation.
        The total number of tasks that have been completed so far.  May be null if the tasks are not easily quantifiable.  Will change as the operation progresses.  May be fractional if a task is partially complete.  All tasks completed does not necessarily mean the operation has completed, there may be additional work.

        Parameters
        ----------
        number_of_completed_tasks: float | None | Unset_Type
            The number_of_completed_tasks of this GsaLongRunningOperation.
        """
        self._number_of_completed_tasks = number_of_completed_tasks

    @property
    def number_of_tasks(self) -> "int | None | Unset_Type":
        """Gets the number_of_tasks of this GsaLongRunningOperation.
        The total number of tasks to be completed.  May be null if the tasks are not easily quantifiable, or if the total number of tasks is not known.  May change as the operation progresses.

        Returns
        -------
        int | None | Unset_Type
            The number_of_tasks of this GsaLongRunningOperation.
        """
        return self._number_of_tasks

    @number_of_tasks.setter
    def number_of_tasks(self, number_of_tasks: "int | None | Unset_Type") -> None:
        """Sets the number_of_tasks of this GsaLongRunningOperation.
        The total number of tasks to be completed.  May be null if the tasks are not easily quantifiable, or if the total number of tasks is not known.  May change as the operation progresses.

        Parameters
        ----------
        number_of_tasks: int | None | Unset_Type
            The number_of_tasks of this GsaLongRunningOperation.
        """
        self._number_of_tasks = number_of_tasks

    @property
    def http_status_code(self) -> "int | None | Unset_Type":
        """Gets the http_status_code of this GsaLongRunningOperation.
        Will not be set if the operation has not completed.

        Returns
        -------
        int | None | Unset_Type
            The http_status_code of this GsaLongRunningOperation.
        """
        return self._http_status_code

    @http_status_code.setter
    def http_status_code(self, http_status_code: "int | None | Unset_Type") -> None:
        """Sets the http_status_code of this GsaLongRunningOperation.
        Will not be set if the operation has not completed.

        Parameters
        ----------
        http_status_code: int | None | Unset_Type
            The http_status_code of this GsaLongRunningOperation.
        """
        self._http_status_code = http_status_code

    @property
    def response(self) -> "object | None | Unset_Type":
        """Gets the response of this GsaLongRunningOperation.
        Will not be set if the operation has not completed.  Could be a success response or an error response depending on whether the operation succeeded or failed.  The response may be null, depending on the operation.

        Returns
        -------
        object | None | Unset_Type
            The response of this GsaLongRunningOperation.
        """
        return self._response

    @response.setter
    def response(self, response: "object | None | Unset_Type") -> None:
        """Sets the response of this GsaLongRunningOperation.
        Will not be set if the operation has not completed.  Could be a success response or an error response depending on whether the operation succeeded or failed.  The response may be null, depending on the operation.

        Parameters
        ----------
        response: object | None | Unset_Type
            The response of this GsaLongRunningOperation.
        """
        self._response = response

    @classmethod
    def get_real_child_model(cls, data: dict[str, str]) -> str:
        """Raises a NotImplementedError for a type without a discriminator defined.

        Parameters
        ----------
        data: ModelBase
            Object representing a subclass of this class

        Raises
        ------
        NotImplementedError
            This class has no discriminator, and hence no subclasses
        """
        raise NotImplementedError()

    def __repr__(self) -> str:
        """For 'print' and 'pprint'"""
        return self.to_str()

    def __eq__(self, other: Any) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, GsaLongRunningOperation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
