# coding: utf-8

"""
    MI Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401
from . import ModelBase


class GrantaServerApiSearchSearchRequest(ModelBase):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'criterion': 'GrantaServerApiSearchCriterion',
        'sort_criteria': 'list[GrantaServerApiSearchSortCriterion]',
        'paging_options': 'GrantaServerApiSearchPagingOptions'
    }

    attribute_map = {
        'criterion': 'criterion',
        'sort_criteria': 'sortCriteria',
        'paging_options': 'pagingOptions'
    }

    subtype_mapping = {
        'criterion': 'GrantaServerApiSearchCriterion',
        'sortCriteria': 'GrantaServerApiSearchSortCriterion',
        'pagingOptions': 'GrantaServerApiSearchPagingOptions'
    }


    def __init__(self, criterion=None, sort_criteria=None, paging_options=None):  # noqa: E501
        """GrantaServerApiSearchSearchRequest - a model defined in Swagger"""  # noqa: E501
        self._criterion = None
        self._sort_criteria = None
        self._paging_options = None
        self.discriminator = None
        if criterion is not None:
            self.criterion = criterion
        if sort_criteria is not None:
            self.sort_criteria = sort_criteria
        if paging_options is not None:
            self.paging_options = paging_options

    @property
    def criterion(self):
        """Gets the criterion of this GrantaServerApiSearchSearchRequest.  # noqa: E501

        :return: The criterion of this GrantaServerApiSearchSearchRequest.  # noqa: E501
        :rtype: GrantaServerApiSearchCriterion
        """
        return self._criterion

    @criterion.setter
    def criterion(self, criterion):
        """Sets the criterion of this GrantaServerApiSearchSearchRequest.

        :param criterion: The criterion of this GrantaServerApiSearchSearchRequest.  # noqa: E501
        :type: GrantaServerApiSearchCriterion
        """
        self._criterion = criterion

    @property
    def sort_criteria(self):
        """Gets the sort_criteria of this GrantaServerApiSearchSearchRequest.  # noqa: E501
        An optional set of attribute based sort criteria. If none are provided, the results will be sorted in descending relevance order.  # noqa: E501

        :return: The sort_criteria of this GrantaServerApiSearchSearchRequest.  # noqa: E501
        :rtype: list[GrantaServerApiSearchSortCriterion]
        """
        return self._sort_criteria

    @sort_criteria.setter
    def sort_criteria(self, sort_criteria):
        """Sets the sort_criteria of this GrantaServerApiSearchSearchRequest.
        An optional set of attribute based sort criteria. If none are provided, the results will be sorted in descending relevance order.  # noqa: E501

        :param sort_criteria: The sort_criteria of this GrantaServerApiSearchSearchRequest.  # noqa: E501
        :type: list[GrantaServerApiSearchSortCriterion]
        """
        self._sort_criteria = sort_criteria

    @property
    def paging_options(self):
        """Gets the paging_options of this GrantaServerApiSearchSearchRequest.  # noqa: E501

        :return: The paging_options of this GrantaServerApiSearchSearchRequest.  # noqa: E501
        :rtype: GrantaServerApiSearchPagingOptions
        """
        return self._paging_options

    @paging_options.setter
    def paging_options(self, paging_options):
        """Sets the paging_options of this GrantaServerApiSearchSearchRequest.

        :param paging_options: The paging_options of this GrantaServerApiSearchSearchRequest.  # noqa: E501
        :type: GrantaServerApiSearchPagingOptions
        """
        self._paging_options = paging_options

    def get_real_child_model(self, data):
        """Raises a NotImplementedError for a type without a discriminator defined."""
        raise NotImplementedError()

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr in self.swagger_types.keys():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GrantaServerApiSearchSearchRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GrantaServerApiSearchSearchRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
