"""
    MI Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from enum import Enum


class GrantaServerApiExceptionsDataModificationReferencedByType(Enum):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Allowed Enum values
    """
    UNKNOWN = "unknown"
    EXPRESSION = "expression"
    VERSIONCONTROLLEDDATA = "versionControlledData"
    DYNAMICLINKGROUP = "dynamicLinkGroup"
    TABULARATTRIBUTE = "tabularAttribute"
    XYCHARTTEMPLATE = "xyChartTemplate"
    SEARCHMASK = "searchMask"
    SECURITYATTRIBUTE = "securityAttribute"
    ATTRIBUTE = "attribute"
    DATA = "data"
    DEFAULTPARAMETERVALUE = "defaultParameterValue"
