# coding: utf-8

"""
    MI Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401
from . import ModelBase

from ansys.grantami.serverapi_openapi.models.granta_server_api_schema_layouts_new_layout_item import GrantaServerApiSchemaLayoutsNewLayoutItem  # noqa: F401,E501

class GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem(GrantaServerApiSchemaLayoutsNewLayoutItem):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'item_type': 'str',
        'source_database_guid': 'str',
        'source_table_guid': 'str',
        'link_group_guid': 'str'
    }
    if hasattr(GrantaServerApiSchemaLayoutsNewLayoutItem, "swagger_types"):
        swagger_types.update(GrantaServerApiSchemaLayoutsNewLayoutItem.swagger_types)

    attribute_map = {
        'item_type': 'itemType',
        'source_database_guid': 'sourceDatabaseGuid',
        'source_table_guid': 'sourceTableGuid',
        'link_group_guid': 'linkGroupGuid'
    }
    if hasattr(GrantaServerApiSchemaLayoutsNewLayoutItem, "attribute_map"):
        attribute_map.update(GrantaServerApiSchemaLayoutsNewLayoutItem.attribute_map)

    subtype_mapping = {
    }


    def __init__(self, item_type='crossDatabaseLink', source_database_guid=None, source_table_guid=None, link_group_guid=None, *args, **kwargs):  # noqa: E501
        """GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem - a model defined in Swagger"""  # noqa: E501
        GrantaServerApiSchemaLayoutsNewLayoutItem.__init__(self, *args, **kwargs)
        self._item_type = None
        self._source_database_guid = None
        self._source_table_guid = None
        self._link_group_guid = None
        self.discriminator = None
        self.item_type = item_type
        if source_database_guid is not None:
            self.source_database_guid = source_database_guid
        if source_table_guid is not None:
            self.source_table_guid = source_table_guid
        if link_group_guid is not None:
            self.link_group_guid = link_group_guid

    @property
    def item_type(self):
        """Gets the item_type of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.  # noqa: E501

        :return: The item_type of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.  # noqa: E501
        :rtype: str
        """
        return self._item_type

    @item_type.setter
    def item_type(self, item_type):
        """Sets the item_type of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.

        :param item_type: The item_type of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.  # noqa: E501
        :type: str
        """
        if item_type is None:
            raise ValueError("Invalid value for `item_type`, must not be `None`")  # noqa: E501
        self._item_type = item_type

    @property
    def source_database_guid(self):
        """Gets the source_database_guid of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.  # noqa: E501

        :return: The source_database_guid of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.  # noqa: E501
        :rtype: str
        """
        return self._source_database_guid

    @source_database_guid.setter
    def source_database_guid(self, source_database_guid):
        """Sets the source_database_guid of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.

        :param source_database_guid: The source_database_guid of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.  # noqa: E501
        :type: str
        """
        self._source_database_guid = source_database_guid

    @property
    def source_table_guid(self):
        """Gets the source_table_guid of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.  # noqa: E501

        :return: The source_table_guid of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.  # noqa: E501
        :rtype: str
        """
        return self._source_table_guid

    @source_table_guid.setter
    def source_table_guid(self, source_table_guid):
        """Sets the source_table_guid of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.

        :param source_table_guid: The source_table_guid of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.  # noqa: E501
        :type: str
        """
        self._source_table_guid = source_table_guid

    @property
    def link_group_guid(self):
        """Gets the link_group_guid of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.  # noqa: E501

        :return: The link_group_guid of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.  # noqa: E501
        :rtype: str
        """
        return self._link_group_guid

    @link_group_guid.setter
    def link_group_guid(self, link_group_guid):
        """Sets the link_group_guid of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.

        :param link_group_guid: The link_group_guid of this GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem.  # noqa: E501
        :type: str
        """
        self._link_group_guid = link_group_guid

    def get_real_child_model(self, data):
        """Raises a NotImplementedError for a type without a discriminator defined."""
        raise NotImplementedError()

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr in self.swagger_types.keys():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GrantaServerApiSchemaLayoutsNewLayoutCrossDatabaseLinkItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
