"""
    MI Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import (
    TYPE_CHECKING,
    Any,
    Dict,
    List,
    BinaryIO,
    Optional,
    Union,
)  # noqa: F401

from . import ModelBase
from ansys.grantami.serverapi_openapi.models.granta_server_api_search_sort_criterion import (
    GrantaServerApiSearchSortCriterion,
)  # noqa: F401


if TYPE_CHECKING:
    from datetime import datetime
    import pathlib
    from . import *


class GrantaServerApiSearchAttributeSortCriterion(GrantaServerApiSearchSortCriterion):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes
    ----------
    swagger_types: Dict[str, str]
        The key is attribute name and the value is attribute type.
    attribute_map: Dict[str, str]
        The key is attribute name and the value is json key in definition.
    subtype_mapping: Dict[str, str]
        The key is the unmangled property name and the value is the corresponding type.
    discriminator: Optional[str]
        Name of the property used as discriminator for subtypes.
    """
    swagger_types: Dict[str, str] = {
        "attribute_type": "GrantaServerApiAttributeType",
        "guid": "str",
        "identity": "int",
        "sort_direction": "GrantaServerApiSearchSortDirection",
        "sort_type": "GrantaServerApiSearchSortType",
        "type": "str",
    }

    attribute_map: Dict[str, str] = {
        "attribute_type": "attributeType",
        "guid": "guid",
        "identity": "identity",
        "sort_direction": "sortDirection",
        "sort_type": "sortType",
        "type": "type",
    }

    subtype_mapping: Dict[str, str] = {
        "attributeType": "GrantaServerApiAttributeType",
        "sortType": "GrantaServerApiSearchSortType",
    }

    discriminator: Optional[str] = None

    def __init__(
        self,
        *,
        attribute_type: "Optional[GrantaServerApiAttributeType]" = None,
        guid: "Optional[str]" = None,
        identity: "Optional[int]" = None,
        sort_direction: "Optional[GrantaServerApiSearchSortDirection]" = None,
        sort_type: "Optional[GrantaServerApiSearchSortType]" = None,
        type: "str" = "attribute",
    ) -> None:
        """GrantaServerApiSearchAttributeSortCriterion - a model defined in Swagger

        Parameters
        ----------
            attribute_type: GrantaServerApiAttributeType, optional
            guid: str, optional
            identity: int, optional
            sort_direction: GrantaServerApiSearchSortDirection, optional
            sort_type: GrantaServerApiSearchSortType, optional
            type: str
        """
        super().__init__(sort_direction=sort_direction)
        self._identity = None
        self._guid = None
        self._attribute_type = None
        self._sort_type = None
        self._type: str = None  # type: ignore[assignment]

        if identity is not None:
            self.identity = identity
        if guid is not None:
            self.guid = guid
        if attribute_type is not None:
            self.attribute_type = attribute_type
        if sort_type is not None:
            self.sort_type = sort_type
        self.type = type

    @property
    def identity(self) -> "Optional[int]":
        """Gets the identity of this GrantaServerApiSearchAttributeSortCriterion.

        Returns
        -------
        int
            The identity of this GrantaServerApiSearchAttributeSortCriterion.
        """
        return self._identity

    @identity.setter
    def identity(self, identity: "Optional[int]") -> None:
        """Sets the identity of this GrantaServerApiSearchAttributeSortCriterion.

        Parameters
        ----------
        identity: int
            The identity of this GrantaServerApiSearchAttributeSortCriterion.
        """
        self._identity = identity

    @property
    def guid(self) -> "Optional[str]":
        """Gets the guid of this GrantaServerApiSearchAttributeSortCriterion.

        Returns
        -------
        str
            The guid of this GrantaServerApiSearchAttributeSortCriterion.
        """
        return self._guid

    @guid.setter
    def guid(self, guid: "Optional[str]") -> None:
        """Sets the guid of this GrantaServerApiSearchAttributeSortCriterion.

        Parameters
        ----------
        guid: str
            The guid of this GrantaServerApiSearchAttributeSortCriterion.
        """
        self._guid = guid

    @property
    def attribute_type(self) -> "Optional[GrantaServerApiAttributeType]":
        """Gets the attribute_type of this GrantaServerApiSearchAttributeSortCriterion.

        Returns
        -------
        GrantaServerApiAttributeType
            The attribute_type of this GrantaServerApiSearchAttributeSortCriterion.
        """
        return self._attribute_type

    @attribute_type.setter
    def attribute_type(
        self, attribute_type: "Optional[GrantaServerApiAttributeType]"
    ) -> None:
        """Sets the attribute_type of this GrantaServerApiSearchAttributeSortCriterion.

        Parameters
        ----------
        attribute_type: GrantaServerApiAttributeType
            The attribute_type of this GrantaServerApiSearchAttributeSortCriterion.
        """
        self._attribute_type = attribute_type

    @property
    def sort_type(self) -> "Optional[GrantaServerApiSearchSortType]":
        """Gets the sort_type of this GrantaServerApiSearchAttributeSortCriterion.

        Returns
        -------
        GrantaServerApiSearchSortType
            The sort_type of this GrantaServerApiSearchAttributeSortCriterion.
        """
        return self._sort_type

    @sort_type.setter
    def sort_type(self, sort_type: "Optional[GrantaServerApiSearchSortType]") -> None:
        """Sets the sort_type of this GrantaServerApiSearchAttributeSortCriterion.

        Parameters
        ----------
        sort_type: GrantaServerApiSearchSortType
            The sort_type of this GrantaServerApiSearchAttributeSortCriterion.
        """
        self._sort_type = sort_type

    @property
    def type(self) -> "str":
        """Gets the type of this GrantaServerApiSearchAttributeSortCriterion.

        Returns
        -------
        str
            The type of this GrantaServerApiSearchAttributeSortCriterion.
        """
        return self._type

    @type.setter
    def type(self, type: "str") -> None:
        """Sets the type of this GrantaServerApiSearchAttributeSortCriterion.

        Parameters
        ----------
        type: str
            The type of this GrantaServerApiSearchAttributeSortCriterion.
        """
        if type is None:
            raise ValueError("Invalid value for 'type', must not be 'None'")
        self._type = type

    @classmethod
    def get_real_child_model(cls, data: ModelBase) -> str:
        """Raises a NotImplementedError for a type without a discriminator defined.

        Parameters
        ----------
        data: ModelBase
            Object representing a subclass of this class

        Raises
        ------
        NotImplementedError
            This class has no discriminator, and hence no subclasses
        """
        raise NotImplementedError()

    def __repr__(self) -> str:
        """For 'print' and 'pprint'"""
        return self.to_str()  # type: ignore[no-any-return]

    def __eq__(self, other: Any) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, GrantaServerApiSearchAttributeSortCriterion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
