# coding: utf-8

"""
    MI Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401
from . import ModelBase


class GrantaServerApiSchemaParametersParameter(ModelBase):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'help_path': 'str',
        'display_names': 'dict(str, str)',
        'name': 'str',
        'guid': 'str'
    }

    attribute_map = {
        'help_path': 'helpPath',
        'display_names': 'displayNames',
        'name': 'name',
        'guid': 'guid'
    }

    subtype_mapping = {
    }

    discriminator_value_class_map = {
        'discrete'.lower(): '#/components/schemas/GrantaServerApiSchemaParametersDiscreteParameter',
        'numeric'.lower(): '#/components/schemas/GrantaServerApiSchemaParametersNumericParameter',
    }

    def __init__(self, help_path=None, display_names=None, name=None, guid=None):  # noqa: E501
        """GrantaServerApiSchemaParametersParameter - a model defined in Swagger"""  # noqa: E501
        self._help_path = None
        self._display_names = None
        self._name = None
        self._guid = None
        self.discriminator = 'type'
        if help_path is not None:
            self.help_path = help_path
        if display_names is not None:
            self.display_names = display_names
        if name is not None:
            self.name = name
        if guid is not None:
            self.guid = guid

    @property
    def help_path(self):
        """Gets the help_path of this GrantaServerApiSchemaParametersParameter.  # noqa: E501

        :return: The help_path of this GrantaServerApiSchemaParametersParameter.  # noqa: E501
        :rtype: str
        """
        return self._help_path

    @help_path.setter
    def help_path(self, help_path):
        """Sets the help_path of this GrantaServerApiSchemaParametersParameter.

        :param help_path: The help_path of this GrantaServerApiSchemaParametersParameter.  # noqa: E501
        :type: str
        """
        self._help_path = help_path

    @property
    def display_names(self):
        """Gets the display_names of this GrantaServerApiSchemaParametersParameter.  # noqa: E501

        :return: The display_names of this GrantaServerApiSchemaParametersParameter.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._display_names

    @display_names.setter
    def display_names(self, display_names):
        """Sets the display_names of this GrantaServerApiSchemaParametersParameter.

        :param display_names: The display_names of this GrantaServerApiSchemaParametersParameter.  # noqa: E501
        :type: dict(str, str)
        """
        self._display_names = display_names

    @property
    def name(self):
        """Gets the name of this GrantaServerApiSchemaParametersParameter.  # noqa: E501

        :return: The name of this GrantaServerApiSchemaParametersParameter.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GrantaServerApiSchemaParametersParameter.

        :param name: The name of this GrantaServerApiSchemaParametersParameter.  # noqa: E501
        :type: str
        """
        self._name = name

    @property
    def guid(self):
        """Gets the guid of this GrantaServerApiSchemaParametersParameter.  # noqa: E501

        :return: The guid of this GrantaServerApiSchemaParametersParameter.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this GrantaServerApiSchemaParametersParameter.

        :param guid: The guid of this GrantaServerApiSchemaParametersParameter.  # noqa: E501
        :type: str
        """
        self._guid = guid

    def get_real_child_model(self, data):
        """Returns the real base class specified by the discriminator"""
        discriminator_value = str(data[self._get_discriminator_field_name()]).lower()
        # The actual class name is not available in swagger-codegen, 
        # so we have to extract it from the JSON reference
        return self.discriminator_value_class_map.get(discriminator_value).rsplit("/", 1)[-1]

    def _get_discriminator_field_name(self):
        name_tokens = self.discriminator.split("_")
        later_tokens = [element.capitalize() for element in name_tokens[1:]]
        return "".join([name_tokens[0], *later_tokens])

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr in self.swagger_types.keys():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GrantaServerApiSchemaParametersParameter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GrantaServerApiSchemaParametersParameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
