# coding: utf-8

"""
    MI Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401
from . import ModelBase


class GrantaServerApiDataExportExportFailure(ModelBase):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'failure_reason': 'str',
        'failed_records': 'list[GrantaServerApiIntegrationDataExportRecordReference]'
    }

    attribute_map = {
        'failure_reason': 'failureReason',
        'failed_records': 'failedRecords'
    }

    subtype_mapping = {
        'failedRecords': 'GrantaServerApiIntegrationDataExportRecordReference'
    }


    def __init__(self, failure_reason=None, failed_records=None):  # noqa: E501
        """GrantaServerApiDataExportExportFailure - a model defined in Swagger"""  # noqa: E501
        self._failure_reason = None
        self._failed_records = None
        self.discriminator = None
        if failure_reason is not None:
            self.failure_reason = failure_reason
        if failed_records is not None:
            self.failed_records = failed_records

    @property
    def failure_reason(self):
        """Gets the failure_reason of this GrantaServerApiDataExportExportFailure.  # noqa: E501

        :return: The failure_reason of this GrantaServerApiDataExportExportFailure.  # noqa: E501
        :rtype: str
        """
        return self._failure_reason

    @failure_reason.setter
    def failure_reason(self, failure_reason):
        """Sets the failure_reason of this GrantaServerApiDataExportExportFailure.

        :param failure_reason: The failure_reason of this GrantaServerApiDataExportExportFailure.  # noqa: E501
        :type: str
        """
        self._failure_reason = failure_reason

    @property
    def failed_records(self):
        """Gets the failed_records of this GrantaServerApiDataExportExportFailure.  # noqa: E501

        :return: The failed_records of this GrantaServerApiDataExportExportFailure.  # noqa: E501
        :rtype: list[GrantaServerApiIntegrationDataExportRecordReference]
        """
        return self._failed_records

    @failed_records.setter
    def failed_records(self, failed_records):
        """Sets the failed_records of this GrantaServerApiDataExportExportFailure.

        :param failed_records: The failed_records of this GrantaServerApiDataExportExportFailure.  # noqa: E501
        :type: list[GrantaServerApiIntegrationDataExportRecordReference]
        """
        self._failed_records = failed_records

    def get_real_child_model(self, data):
        """Raises a NotImplementedError for a type without a discriminator defined."""
        raise NotImplementedError()

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr in self.swagger_types.keys():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GrantaServerApiDataExportExportFailure, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GrantaServerApiDataExportExportFailure):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
