# coding: utf-8

"""
    MI Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from . import ApiBase


class ListPermissionsApi(ApiBase):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def api_v1_lists_list_list_identifier_permissions_get(self, list_identifier, **kwargs):  # noqa: E501
        """Gets all permissions associated with the specified list.  # noqa: E501

        This method makes a synchronous HTTP request.

        :param str list_identifier: (required)
        :return: list[GrantaServerApiListsDtoUserPermissionDto]
        """
        kwargs['_return_http_data_only'] = True
        (data) = self.api_v1_lists_list_list_identifier_permissions_get_with_http_info(list_identifier, **kwargs)  # noqa: E501
        return data

    def api_v1_lists_list_list_identifier_permissions_get_with_http_info(self, list_identifier, **kwargs):  # noqa: E501
        """Gets all permissions associated with the specified list.  # noqa: E501

        This method makes a synchronous HTTP request.

        :param str list_identifier: (required)
        :return: list[GrantaServerApiListsDtoUserPermissionDto]
        """

        all_params = ['list_identifier']  # noqa: E501
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in params['kwargs'].items():
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '{}' to method api_v1_lists_list_list_identifier_permissions_get".format(key)
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'list_identifier' is set
        if ('list_identifier' not in params or
                params['list_identifier'] is None):
            raise ValueError("Missing the required parameter `list_identifier` when calling `api_v1_lists_list_list_identifier_permissions_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'list_identifier' in params:
            path_params['listIdentifier'] = params['list_identifier']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501
        
        response_type_map = {
            200: 'list[GrantaServerApiListsDtoUserPermissionDto]',
            403: None,
            404: None,
        }
        
        return self.api_client.call_api(
            '/api/v1/lists/list/{listIdentifier}/permissions', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats,
            response_type_map=response_type_map)

    def api_v1_lists_list_list_identifier_permissions_post(self, list_identifier, **kwargs):  # noqa: E501
        """Sets permissions for the specified list. Returns a collection of the created/updated permissions.  # noqa: E501

        This method makes a synchronous HTTP request.

        :param str list_identifier: (required)
        :param list[GrantaServerApiListsDtoUserPermissionInputDto] body:
        :return: list[GrantaServerApiListsDtoUserPermissionDto]
        """
        kwargs['_return_http_data_only'] = True
        (data) = self.api_v1_lists_list_list_identifier_permissions_post_with_http_info(list_identifier, **kwargs)  # noqa: E501
        return data

    def api_v1_lists_list_list_identifier_permissions_post_with_http_info(self, list_identifier, **kwargs):  # noqa: E501
        """Sets permissions for the specified list. Returns a collection of the created/updated permissions.  # noqa: E501

        This method makes a synchronous HTTP request.

        :param str list_identifier: (required)
        :param list[GrantaServerApiListsDtoUserPermissionInputDto] body:
        :return: list[GrantaServerApiListsDtoUserPermissionDto]
        """

        all_params = ['list_identifier', 'body']  # noqa: E501
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in params['kwargs'].items():
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '{}' to method api_v1_lists_list_list_identifier_permissions_post".format(key)
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'list_identifier' is set
        if ('list_identifier' not in params or
                params['list_identifier'] is None):
            raise ValueError("Missing the required parameter `list_identifier` when calling `api_v1_lists_list_list_identifier_permissions_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'list_identifier' in params:
            path_params['listIdentifier'] = params['list_identifier']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501
        
        response_type_map = {
            202: 'list[GrantaServerApiListsDtoUserPermissionDto]',
            400: None,
            403: None,
            404: None,
        }
        
        return self.api_client.call_api(
            '/api/v1/lists/list/{listIdentifier}/permissions', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats,
            response_type_map=response_type_map)

    def api_v1_lists_list_list_identifier_permissions_subscribe_post(self, list_identifier, **kwargs):  # noqa: E501
        """Subscribes the calling user to the specified list.  # noqa: E501

        This method makes a synchronous HTTP request.

        :param str list_identifier: (required)
        :return: GrantaServerApiListsDtoUserPermissionDto
        """
        kwargs['_return_http_data_only'] = True
        (data) = self.api_v1_lists_list_list_identifier_permissions_subscribe_post_with_http_info(list_identifier, **kwargs)  # noqa: E501
        return data

    def api_v1_lists_list_list_identifier_permissions_subscribe_post_with_http_info(self, list_identifier, **kwargs):  # noqa: E501
        """Subscribes the calling user to the specified list.  # noqa: E501

        This method makes a synchronous HTTP request.

        :param str list_identifier: (required)
        :return: GrantaServerApiListsDtoUserPermissionDto
        """

        all_params = ['list_identifier']  # noqa: E501
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in params['kwargs'].items():
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '{}' to method api_v1_lists_list_list_identifier_permissions_subscribe_post".format(key)
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'list_identifier' is set
        if ('list_identifier' not in params or
                params['list_identifier'] is None):
            raise ValueError("Missing the required parameter `list_identifier` when calling `api_v1_lists_list_list_identifier_permissions_subscribe_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'list_identifier' in params:
            path_params['listIdentifier'] = params['list_identifier']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501
        
        response_type_map = {
            202: 'GrantaServerApiListsDtoUserPermissionDto',
            400: None,
            403: None,
            404: None,
        }
        
        return self.api_client.call_api(
            '/api/v1/lists/list/{listIdentifier}/permissions/subscribe', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats,
            response_type_map=response_type_map)

    def api_v1_lists_list_list_identifier_permissions_unsubscribe_post(self, list_identifier, **kwargs):  # noqa: E501
        """Unsubscribes the calling user from the specified list.  # noqa: E501

        This method makes a synchronous HTTP request.

        :param str list_identifier: (required)
        :return: GrantaServerApiListsDtoUserPermissionDto
        """
        kwargs['_return_http_data_only'] = True
        (data) = self.api_v1_lists_list_list_identifier_permissions_unsubscribe_post_with_http_info(list_identifier, **kwargs)  # noqa: E501
        return data

    def api_v1_lists_list_list_identifier_permissions_unsubscribe_post_with_http_info(self, list_identifier, **kwargs):  # noqa: E501
        """Unsubscribes the calling user from the specified list.  # noqa: E501

        This method makes a synchronous HTTP request.

        :param str list_identifier: (required)
        :return: GrantaServerApiListsDtoUserPermissionDto
        """

        all_params = ['list_identifier']  # noqa: E501
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in params['kwargs'].items():
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '{}' to method api_v1_lists_list_list_identifier_permissions_unsubscribe_post".format(key)
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'list_identifier' is set
        if ('list_identifier' not in params or
                params['list_identifier'] is None):
            raise ValueError("Missing the required parameter `list_identifier` when calling `api_v1_lists_list_list_identifier_permissions_unsubscribe_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'list_identifier' in params:
            path_params['listIdentifier'] = params['list_identifier']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501
        
        response_type_map = {
            202: 'GrantaServerApiListsDtoUserPermissionDto',
            400: None,
            403: None,
            404: None,
        }
        
        return self.api_client.call_api(
            '/api/v1/lists/list/{listIdentifier}/permissions/unsubscribe', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats,
            response_type_map=response_type_map)

    def api_v1_lists_list_list_identifier_permissions_user_user_identifier_get(self, list_identifier, user_identifier, **kwargs):  # noqa: E501
        """Gets the permission flags of the permission associating the specified list with the specified user.  # noqa: E501

        This method makes a synchronous HTTP request.

        :param str list_identifier: (required)
        :param str user_identifier: (required)
        :return: GrantaServerApiListsDtoRecordListPermissionFlagsDto
        """
        kwargs['_return_http_data_only'] = True
        (data) = self.api_v1_lists_list_list_identifier_permissions_user_user_identifier_get_with_http_info(list_identifier, user_identifier, **kwargs)  # noqa: E501
        return data

    def api_v1_lists_list_list_identifier_permissions_user_user_identifier_get_with_http_info(self, list_identifier, user_identifier, **kwargs):  # noqa: E501
        """Gets the permission flags of the permission associating the specified list with the specified user.  # noqa: E501

        This method makes a synchronous HTTP request.

        :param str list_identifier: (required)
        :param str user_identifier: (required)
        :return: GrantaServerApiListsDtoRecordListPermissionFlagsDto
        """

        all_params = ['list_identifier', 'user_identifier']  # noqa: E501
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in params['kwargs'].items():
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '{}' to method api_v1_lists_list_list_identifier_permissions_user_user_identifier_get".format(key)
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'list_identifier' is set
        if ('list_identifier' not in params or
                params['list_identifier'] is None):
            raise ValueError("Missing the required parameter `list_identifier` when calling `api_v1_lists_list_list_identifier_permissions_user_user_identifier_get`")  # noqa: E501
        # verify the required parameter 'user_identifier' is set
        if ('user_identifier' not in params or
                params['user_identifier'] is None):
            raise ValueError("Missing the required parameter `user_identifier` when calling `api_v1_lists_list_list_identifier_permissions_user_user_identifier_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'list_identifier' in params:
            path_params['listIdentifier'] = params['list_identifier']  # noqa: E501
        if 'user_identifier' in params:
            path_params['userIdentifier'] = params['user_identifier']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501
        
        response_type_map = {
            200: 'GrantaServerApiListsDtoRecordListPermissionFlagsDto',
            403: None,
            404: None,
        }
        
        return self.api_client.call_api(
            '/api/v1/lists/list/{listIdentifier}/permissions/user/{userIdentifier}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats,
            response_type_map=response_type_map)

    def api_v1_lists_list_list_identifier_permissions_user_user_identifier_put(self, list_identifier, user_identifier, **kwargs):  # noqa: E501
        """Sets the permission flags of the permission associating the specified list with the specified user.  # noqa: E501

        This method makes a synchronous HTTP request.

        :param str list_identifier: (required)
        :param str user_identifier: (required)
        :param GrantaServerApiListsDtoRecordListPermissionFlagsDto body:
        :return: GrantaServerApiListsDtoRecordListPermissionFlagsDto
        """
        kwargs['_return_http_data_only'] = True
        (data) = self.api_v1_lists_list_list_identifier_permissions_user_user_identifier_put_with_http_info(list_identifier, user_identifier, **kwargs)  # noqa: E501
        return data

    def api_v1_lists_list_list_identifier_permissions_user_user_identifier_put_with_http_info(self, list_identifier, user_identifier, **kwargs):  # noqa: E501
        """Sets the permission flags of the permission associating the specified list with the specified user.  # noqa: E501

        This method makes a synchronous HTTP request.

        :param str list_identifier: (required)
        :param str user_identifier: (required)
        :param GrantaServerApiListsDtoRecordListPermissionFlagsDto body:
        :return: GrantaServerApiListsDtoRecordListPermissionFlagsDto
        """

        all_params = ['list_identifier', 'user_identifier', 'body']  # noqa: E501
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in params['kwargs'].items():
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '{}' to method api_v1_lists_list_list_identifier_permissions_user_user_identifier_put".format(key)
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'list_identifier' is set
        if ('list_identifier' not in params or
                params['list_identifier'] is None):
            raise ValueError("Missing the required parameter `list_identifier` when calling `api_v1_lists_list_list_identifier_permissions_user_user_identifier_put`")  # noqa: E501
        # verify the required parameter 'user_identifier' is set
        if ('user_identifier' not in params or
                params['user_identifier'] is None):
            raise ValueError("Missing the required parameter `user_identifier` when calling `api_v1_lists_list_list_identifier_permissions_user_user_identifier_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'list_identifier' in params:
            path_params['listIdentifier'] = params['list_identifier']  # noqa: E501
        if 'user_identifier' in params:
            path_params['userIdentifier'] = params['user_identifier']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501
        
        response_type_map = {
            201: 'GrantaServerApiListsDtoRecordListPermissionFlagsDto',
            400: None,
            403: None,
            404: None,
        }
        
        return self.api_client.call_api(
            '/api/v1/lists/list/{listIdentifier}/permissions/user/{userIdentifier}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats,
            response_type_map=response_type_map)
