# Copyright (C) 2023 - 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""
MI Server API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import TYPE_CHECKING, Any, BinaryIO, Optional  # noqa: F401

from ansys.grantami.serverapi_openapi.v2027r1.models.gsa_attribute_error_detail import (  # noqa: F401
    GsaAttributeErrorDetail,
)
from ansys.grantami.serverapi_openapi.v2027r1.models.gsa_attribute_error_reason import (
    GsaAttributeErrorReason,
)

from . import ModelBase, Unset, Unset_Type

if TYPE_CHECKING:
    from datetime import datetime
    import pathlib

    from . import *


class GsaNoSuchTabularColumnAttributeErrorDetail(GsaAttributeErrorDetail):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes
    ----------
    swagger_types: dict[str, str]
        The key is attribute name and the value is attribute type.
    attribute_map: dict[str, str]
        The key is attribute name and the value is json key in definition.
    subtype_mapping: dict[str, str]
        The key is the unmangled property name and the value is the corresponding type.
    discriminator: Optional[str]
        Name of the property used as discriminator for subtypes.
    """
    swagger_types: dict[str, str] = {
        "message": "str",
        "reason": "GsaAttributeErrorReason",
        "attribute_guid": "str",
        "column_guid": "str",
        "database_key": "str",
        "table_guid": "str",
    }

    attribute_map: dict[str, str] = {
        "message": "message",
        "reason": "reason",
        "attribute_guid": "attributeGuid",
        "column_guid": "columnGuid",
        "database_key": "databaseKey",
        "table_guid": "tableGuid",
    }

    subtype_mapping: dict[str, str] = {}

    discriminator: Optional[str] = None

    def __init__(
        self,
        *,
        message: "str",
        reason: "GsaAttributeErrorReason" = GsaAttributeErrorReason.NOSUCHTABULARCOLUMN,
        attribute_guid: "str | Unset_Type" = Unset,
        column_guid: "str | Unset_Type" = Unset,
        database_key: "str | None | Unset_Type" = Unset,
        table_guid: "str | Unset_Type" = Unset,
    ) -> None:
        """GsaNoSuchTabularColumnAttributeErrorDetail - a model defined in Swagger

        Parameters
        ----------
        message: str
        reason: GsaAttributeErrorReason
        attribute_guid: str, optional
        column_guid: str, optional
        database_key: str | None, optional
        table_guid: str, optional
        """
        super().__init__(message=message, reason=reason)
        self._database_key: str | None | Unset_Type = Unset
        self._table_guid: str | Unset_Type = Unset
        self._attribute_guid: str | Unset_Type = Unset
        self._column_guid: str | Unset_Type = Unset

        if database_key is not Unset:
            self.database_key = database_key
        if table_guid is not Unset:
            self.table_guid = table_guid
        if attribute_guid is not Unset:
            self.attribute_guid = attribute_guid
        if column_guid is not Unset:
            self.column_guid = column_guid

    @property
    def database_key(self) -> "str | None | Unset_Type":
        """Gets the database_key of this GsaNoSuchTabularColumnAttributeErrorDetail.

        Returns
        -------
        str | None | Unset_Type
            The database_key of this GsaNoSuchTabularColumnAttributeErrorDetail.
        """
        return self._database_key

    @database_key.setter
    def database_key(self, database_key: "str | None | Unset_Type") -> None:
        """Sets the database_key of this GsaNoSuchTabularColumnAttributeErrorDetail.

        Parameters
        ----------
        database_key: str | None | Unset_Type
            The database_key of this GsaNoSuchTabularColumnAttributeErrorDetail.
        """
        self._database_key = database_key

    @property
    def table_guid(self) -> "str | Unset_Type":
        """Gets the table_guid of this GsaNoSuchTabularColumnAttributeErrorDetail.

        Returns
        -------
        str | Unset_Type
            The table_guid of this GsaNoSuchTabularColumnAttributeErrorDetail.
        """
        return self._table_guid

    @table_guid.setter
    def table_guid(self, table_guid: "str | Unset_Type") -> None:
        """Sets the table_guid of this GsaNoSuchTabularColumnAttributeErrorDetail.

        Parameters
        ----------
        table_guid: str | Unset_Type
            The table_guid of this GsaNoSuchTabularColumnAttributeErrorDetail.
        """
        # Field is not nullable
        if table_guid is None:
            raise ValueError("Invalid value for 'table_guid', must not be 'None'")
        self._table_guid = table_guid

    @property
    def attribute_guid(self) -> "str | Unset_Type":
        """Gets the attribute_guid of this GsaNoSuchTabularColumnAttributeErrorDetail.

        Returns
        -------
        str | Unset_Type
            The attribute_guid of this GsaNoSuchTabularColumnAttributeErrorDetail.
        """
        return self._attribute_guid

    @attribute_guid.setter
    def attribute_guid(self, attribute_guid: "str | Unset_Type") -> None:
        """Sets the attribute_guid of this GsaNoSuchTabularColumnAttributeErrorDetail.

        Parameters
        ----------
        attribute_guid: str | Unset_Type
            The attribute_guid of this GsaNoSuchTabularColumnAttributeErrorDetail.
        """
        # Field is not nullable
        if attribute_guid is None:
            raise ValueError("Invalid value for 'attribute_guid', must not be 'None'")
        self._attribute_guid = attribute_guid

    @property
    def column_guid(self) -> "str | Unset_Type":
        """Gets the column_guid of this GsaNoSuchTabularColumnAttributeErrorDetail.

        Returns
        -------
        str | Unset_Type
            The column_guid of this GsaNoSuchTabularColumnAttributeErrorDetail.
        """
        return self._column_guid

    @column_guid.setter
    def column_guid(self, column_guid: "str | Unset_Type") -> None:
        """Sets the column_guid of this GsaNoSuchTabularColumnAttributeErrorDetail.

        Parameters
        ----------
        column_guid: str | Unset_Type
            The column_guid of this GsaNoSuchTabularColumnAttributeErrorDetail.
        """
        # Field is not nullable
        if column_guid is None:
            raise ValueError("Invalid value for 'column_guid', must not be 'None'")
        self._column_guid = column_guid

    @classmethod
    def get_real_child_model(cls, data: dict[str, str]) -> str:
        """Raises a NotImplementedError for a type without a discriminator defined.

        Parameters
        ----------
        data: ModelBase
            Object representing a subclass of this class

        Raises
        ------
        NotImplementedError
            This class has no discriminator, and hence no subclasses
        """
        raise NotImplementedError()

    def __repr__(self) -> str:
        """For 'print' and 'pprint'"""
        return self.to_str()

    def __eq__(self, other: Any) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, GsaNoSuchTabularColumnAttributeErrorDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
